# Generated by Django 3.1 on 2020-09-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
