# Generated by Django 3.1 on 2020-10-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quesAns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-time_stamp']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
