# Generated by Django 3.1 on 2020-10-12 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quesAns', '0002_auto_20201012_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='content',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quesAns.question'),
        ),
    ]
