# Generated by Django 3.1 on 2020-10-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quesAns', '0004_auto_20201025_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='desc',
        ),
    ]
