# Generated by Django 3.1 on 2020-10-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quesAns', '0005_remove_question_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.CharField(default='slug', max_length=200),
            preserve_default=False,
        ),
    ]
