# Generated by Django 3.1 on 2020-10-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quesAns', '0006_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
